# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build
- deploy
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-branch:
  environment: $CI_COMMIT_BRANCH
  image: node:20.11.0
  stage: build
  tags:
  - arch:arm64
  - size:large
  before_script:
    - npm ci --save-dev
  script:
    - echo "Executing build..."
    - npm run build
  artifacts:
    untracked: false
    when: on_success
    expire_in: "30 days"
    paths:
      - ./dist
  cache:
    policy: push
    when: on_success
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - package.json
      - package-lock.json
      - cdk.json

synthesize-stack:
  environment: $CI_COMMIT_BRANCH
  image: node:20.11.0
  stage: build
  tags:
  - arch:arm64
  - size:large
  before_script:
    - echo $DEPLOY_CONFIG > ./dist/bin/config.json
    - npm install --save-dev
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Synthesizing stack..."
    - npx cdk synth
  artifacts:
    paths:
      - ./cdk.out
      - ./dist/bin/config.json
  rules:
    - if: $DEPLOY_CONFIG
  needs:
    - build-branch
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - package.json
      - package-lock.json
      - cdk.json
    
  
ci-deploy-branch:
  environment: $CI_STABLE_ENV_BRANCH
  stage: deploy
  image: node:20.11.0
  tags:
    - arch:arm64
    - size:large
  variables:
    AWS_CREDS_TARGET_ROLE: $CI_AWS_CREDS_TARGET_ROLE
    AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
    GIT_STRATEGY: none
  needs:
    - synthesize-stack
  before_script:
    - npm install -g aws-cdk@latest
  script:
   - echo $(npx cdk diff) > ./cdk-diff.txt
   - cat ./cdk-diff.txt
   - npx cdk --app ./cdk.out deploy --require-approval never
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - ./cdk-diff.txt
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_STABLE_ENV_BRANCH) && $DEPLOY_CONFIG
  cache:
    policy: pull
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
      - package.json
      - package-lock.json
      - cdk.json