# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- build
- deploy
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

build-branch:
  environment: $CI_COMMIT_BRANCH
  image: node:20.11.0
  stage: build
  tags:
  - arch:arm64
  - size:large
  before_script:
    - npm ci
  script:
    - echo "Executing build..."
    - npm run build
    - npx cdk synth
  artifacts:
    paths:
      - ./bin/config.json

synthesize-stack:
  environment: $CI_COMMIT_BRANCH
  image: node:20.11.0
  stage: build
  before_script:
    - echo $DEPLOY_CONFIG > ./bin/config.json
    - npm ci
  script:
    - echo "Synthesizing stack..."
    - npx cdk synth
  artifacts:
    paths:
      - ./cdk.out
  rules:
    - if: $DEPLOY_CONFIG
  dependencies:
    - build-branch
    
  
ci-deploy-branch:
  environment: $CI_STABLE_ENV_BRANCH
  stage: deploy
  image: node:20.11.0
  tags:
    - arch:arm64
    - size:large
  variables:
    AWS_CREDS_TARGET_ROLE: $CI_AWS_CREDS_TARGET_ROLE
    AWS_DEFAULT_REGION: $AWS_DEPLOYMENT_REGION
  dependencies:
    - build-branch
    - synthesize-stack
  before_script:
    - npm ci
    - npm install -g aws-cdk@latest
  script:
   - echo $(npx cdk diff) > ./cdk-diff.txt
   - cat ./cdk-deff.txt
   - npx cdk --app ./cdk.out deploy --require-approval never
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - ./cdk-def.txt
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_STABLE_ENV_BRANCH) && $DEPLOY_CONFIG