name: Build and Synthesize

on:
  push:
    branches:
      - '**'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm ci
        
    - name: Build project
      run: npm run build
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-project
        path: |
          lib/api/functions/out/*
          lib/user-interface/genai-newsletter-ui/dist/*
          
  synthesis:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20
    
    - name: Install dependencies
      run: npm ci
        
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: built-project
    
    - name: Generate Configuration file
      run: echo "${DEPLOY_CONFIG}" > ./bin/config.json
      env:
        DEPLOY_CONFIG: ${{ env.DEPLOY_CONFIG }}
        
    - name: Synthesize CDK
      run: npx cdk synth
      
